AddonId: RomM_9700aa21-447d-41b4-a989-acd38f407d9f
Packages:
  - Version: 0.2.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-03-24
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.1/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_1.pext
    Changelog:
      - Initial beta release of the RomM Library Importer
  - Version: 0.2.2
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-04-05
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.2/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_2.pext
    Changelog:
      - Fix crashes when null igdb_id is returned from RomM for platform
  - Version: 0.2.3
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-06-08
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.3/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_3.pext
    Changelog:
      - Update for API changes in 3.2.0 release of RomM
  - Version: 0.2.4
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-08-02
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.4/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_4.pext
    Changelog:
      - Performance, naming and code quality improvements
  - Version: 0.2.5
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-08-05
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.5/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_5.pext
    Changelog:
      - Fix fetching platforms with missing/null IGDB ID
  - Version: 0.2.6
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-08-15
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.6/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_6.pext
    Changelog:
      - Fix downloading large multi-file roms
  - Version: 0.2.7
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2024-11-20
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.7/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_7.pext
    Changelog:
      - Ensure rom installation paths are initialized correctly upon import
      - Filter registered ROMs by emulator profile supported file types
  - Version: 0.2.8
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2025-01-13
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.2.8/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_2_8.pext
    Changelog:
      - Fix crash when importing ROMs with long last_played_at datetimes\
  - Version: 0.3.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2025-03-11
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.3.0/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_3_0.pext
    Changelog:
      - Update game fetching to support changes in API version 3.8.0
  - Version: 0.3.1
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2025-04-26
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/v0.3.1/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_3_1.pext
    Changelog:
      - Fetch up to 2500 games per platform to avoid timeouts
  - Version: 0.4.0
    RequiredApiVersion: 6.11.0
    ReleaseDate: 2025-06-05
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/0.4.0/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_4_0.pext
    Changelog:
      - Fetch games in pagniated chunks of 72 to avoid timeouts
  - Version: 0.4.1
    RequiredApiVersion: 6.13.0
    ReleaseDate: 2025-11-28
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/0.4.1/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_4_1.pext
    Changelog:
      - Use gameName instead of gameNameWithTags
      - Bump PlayniteSDK from 6.11.0 to 6.13.0
  - Version: 0.5.0
    RequiredApiVersion: 6.15.0
    ReleaseDate: 2026-02-02
    PackageUrl: https://github.com/rommapp/playnite-plugin/releases/download/0.5.0/RomM_9700aa21-447d-41b4-a989-acd38f407d9f_0_5_0.pext
    Changelog:
      - Skip detect .iso files as compressed by @gantoine
      - Update isMulti to HasMultipleFiles field by @gantoine
      - Normalize RomMHost URLs to avoid double slashes by @saitatter
      - Update platform_id to platform_ids by @matthew-pye
      - Implement per mapping m3u support by @matthew-pye
      - Update path handling for playnite portable case by @dravorle
      - Check mappings UseM3u is enabled  by @matthew-pye
      - Added download manager to inspect progress of games download by @saitatter
      - Implement 7z extraction by @matthew-pye
      - Fix incorrectly merged 7z & use more metadata by @matthew-pye
      - Bump PlayniteSDK from 6.13.0 to 6.15.0 by @dependabot
